name: Build

on:
  push:
    branches:
      - main
      - v*
  pull_request:
    branches:
      - main
      - release*
    paths:
      - main.go
      - version.txt
      - internal/**
      - go.mod
      - go.sum

env:
  GO_VERSION: 1.16.7

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - name: Check out
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@0caeaed6fd66a828038c2da3c0f662a42862658f # v1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Go Build
        run: go build ./...
      - name: Run Go Test
        run: go test ./...
